apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-function-app
  labels:
    app: my-function-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-function-app
  template:
    metadata:
      labels:
        app: my-function-app
    spec:
      containers:
      - name: worker-1
        image: mypro543.azurecr.io/sending-msg:8
        securityContext:
          runAsUser: 0
        env:
        - name: AzureWebJobsStorage
          value: "DefaultEndpointsProtocol=https;AccountName=mypro543;AccountKey=EOsReWtTxbt3hIzQLfBr8/UqcEVV0c3Z/Xfehmr4G72G9V42rGnRFEy6VAFu436m7pFjE8gMAjbb+AStNA6zgw==;EndpointSuffix=core.windows.net"
        - name: AzureWebJobsDashboard
          value: "DefaultEndpointsProtocol=https;AccountName=mypro543;AccountKey=EOsReWtTxbt3hIzQLfBr8/UqcEVV0c3Z/Xfehmr4G72G9V42rGnRFEy6VAFu436m7pFjE8gMAjbb+AStNA6zgw==;EndpointSuffix=core.windows.net"
      - name: worker-2
        image: mypro543.azurecr.io/load-msg:8
        securityContext:
          runAsUser: 0
        env:
        - name: AzureWebJobsStorage
          value: "DefaultEndpointsProtocol=https;AccountName=mypro543;AccountKey=EOsReWtTxbt3hIzQLfBr8/UqcEVV0c3Z/Xfehmr4G72G9V42rGnRFEy6VAFu436m7pFjE8gMAjbb+AStNA6zgw==;EndpointSuffix=core.windows.net"
        - name: AzureWebJobsDashboard
          value: "DefaultEndpointsProtocol=https;AccountName=mypro543;AccountKey=EOsReWtTxbt3hIzQLfBr8/UqcEVV0c3Z/Xfehmr4G72G9V42rGnRFEy6VAFu436m7pFjE8gMAjbb+AStNA6zgw==;EndpointSuffix=core.windows.net"
---
apiVersion: v1
kind: Service
metadata:
  name: my-function-app
spec:
  selector:
    app: my-function-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
